marche_en_ligne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Aux jardins gourmands - Administration'
admin.site.index_title = 'Marché en ligne fermier'

handler404 = 'store.views.notfound'

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"),
    path("marcheenligne", views.webmarket, name="webmarket"),
    path("pointsdevente", views.marketplaces, name="marketplaces"),
    path("panier", views.cart, name="cart"),
    path("panier/<str:info>", views.cart, name="cart"),
    path("login", views.login_form, name="login"),
    path("account", views.profil, name="account"),
    path("account/<str:info>", views.profil, name="account"),
    path("logout", views.logout_account, name="logout"),
    path("delete", views.delete_account, name="delete_account"),
    path("cart", views.adding_in_cart, name="adding_cart"),
    path("contact", views.email, name="contact"),
    path("reservation", views.reservation, name="reservation"),
    path("commander", views.command, name="command"),
    path("valid", views.validate_command, name="valid"),
    path("remove", views.remove_order, name="remove"),
]

store/views.py
from django.shortcuts import render, redirect
from store.models import *
from .classes import *
from django.contrib.auth.models import User
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    update_session_auth_hash
)
from django.http import JsonResponse
from django.db import IntegrityError
from django.db.models import F
from django.core.mail import EmailMessage
import datetime
from django.urls import reverse
from django.db import transaction
from django.views.decorators.cache import never_cache

##################


def check_cart_session(request):
    """Check if user has a cart dictionary
    in request.session and create one if not
    """

    if "cart" not in request.session:
        request.session["cart"] = {}


def add_to_cart(request, client, variety, quantity):
    """Add a variety in user cart. If intergity error,
    not create but change quantity of the existing record in cart user
    """

    try:
        Cart.objects.create(
            fk_client=client,
            fk_variety=variety,
            quantity=quantity
        )
    except IntegrityError:
        existing_record = Cart.objects.get(
            fk_client=client,
            fk_variety=variety
        )
        existing_record.quantity = quantity
        existing_record.save()


def update_cart_values(request, client):
    """Compare cart objects with stock and availability of the referenced
    variety. Delete or update depending these conditions
    """

    for obj in Cart.objects.filter(fk_client=client):
        if obj.fk_variety.stock == 0 or obj.fk_variety.available is False:
            obj.delete()

        elif obj.quantity > obj.fk_variety.stock:
            obj.quantity = obj.fk_variety.stock
            obj.save()


def before(request):
    """If the authenticated user is in ready to command list, delete him
    from this and add quantity of his cart items in the stock of referenced
    variety
    """

    if request.user.is_authenticated:
        client = Client.objects.get(user=request.user)
        try:
            ClientReadyToCommand.objects.get(fk_client=client).delete()
            cart = UserCart(client)
            cart.unsave()
        except ClientReadyToCommand.DoesNotExist:
            pass


##################


def index(request):
    """Load index template"""

    before(request)
    return render(request, "store/index.html")


def webmarket(request):
    """Load catalog of available products of the farm. If user has a cart,
    add quantity on variety referenced
    """

    before(request)

    variety = Variety.objects.filter(available=True).order_by('fk_product')
    category = Category.objects.all()

    if request.user.is_authenticated:
        client = Client.objects.get(user=request.user)

        update_cart_values(request, client)

        cart = Cart.objects.filter(fk_client=client)

    else:
        # if user is anonymous, create objects queryset with dict cart session
        check_cart_session(request)
        cart_session = CartSession(request.session.get("cart"))
        cart_session.create_queryset(request)
        request.session["cart"] = cart_session.update(request)
        cart = cart_session.return_queryset(request)

    if cart is not None:
        for elt in variety:
            for record in cart:
                if elt == record.fk_variety:
                    elt.quantity = record.quantity

    context = {"catalog": variety, "filter": category}

    return render(request, "store/webmarket.html", context)


def marketplaces(request):
    """ Load template to display all market places of the farm """

    before(request)
    places = DirectWithdrawal.objects.all()
    locker = CollectLocation.objects.filter(fk_command_type__type="locker")
    restaurant = TimeSlot.objects.filter(fk_command_type__type="delivery")

    context = {"places": places, "locker": locker, "restaurant": restaurant}

    return render(request, "store/marketplaces.html", context)


@never_cache
def cart(request, info="show"):
    """if request method is GET : update cart value of the user depending of the
    stock and availability of varieties and load template to display his cart.

    if request method is POST : remove or update cart with data send by
    AJAX request
    """

    before(request)
    if request.method == "GET":
        if request.user.is_authenticated:
            client = Client.objects.get(user=request.user)
            update_cart_values(request, client)

            query = Cart.objects.filter(fk_client=client)

        else:
            # User is anonymous
            check_cart_session(request)
            cart_session = CartSession(request.session.get("cart"))
            cart_session.create_queryset(request)
            request.session["cart"] = cart_session.update(request)
            query = cart_session.return_queryset(request)

        total_cart = 0
        for product in query:
            product.total = product.quantity * product.fk_variety.price
            total_cart += product.total

        minimum = MinimumCommand.objects.all().first().amount

        if info == "outofstock":
            message = "Votre panier a été modifié en fonction \
            des stocks restants"
        elif info == "expire":
            message = "Votre session a expiré. Veuillez valider \
            à nouveau votre panier"
        else:
            message = ""

        context = {
            "cart": query,
            "total": total_cart,
            "minimum": minimum,
            "message": message,
        }

        return render(request, "store/cart.html", context)

    elif request.method == "POST":
        id_product = request.POST["cart_object"]

        if request.POST["action"] == "remove":

            if request.user.is_authenticated:
                client = Client.objects.get(user=request.user)
                variety_ref = Variety.objects.get(pk=id_product)

                cart_record = Cart.objects.get(
                    fk_client=client,
                    fk_variety=variety_ref
                )
                cart_record.delete()
            else:
                request.session["cart"].pop(id_product)
                request.session.modified = True

        elif request.POST["action"] == "update":
            quantity = request.POST["quantity"]
            stock = Variety.objects.get(pk=id_product).stock

            if request.user.is_authenticated:
                client = Client.objects.get(user=request.user)
                variety_ref = Variety.objects.get(pk=id_product)

                cart_record = Cart.objects.get(
                    fk_client=client,
                    fk_variety=variety_ref
                )

                if int(quantity) <= stock:
                    cart_record.quantity = quantity
                    cart_record.save()

            else:
                if int(quantity) <= stock:
                    request.session["cart"][id_product] = quantity
                    request.session.modified = True

        context = {}

        return JsonResponse(context)


def login_form(request):
    """Connect an existing user or create an account with data send by
    request POST ajax.
    """

    before(request)

    auth_email = request.POST["email"].lower()
    password = request.POST["password"]

    if request.POST["choice"] == "connect":
        try:
            u = User.objects.get(username=auth_email)
            if u.check_password(password):
                user = authenticate(username=auth_email, password=password)
                login(request, user)
                message = "success"

                client = Client.objects.get(user=user)

                check_cart_session(request)
                cart = CartSession(request.session.get("cart"))
                cart.create_queryset(request)
                cart.to_cart_database(request, client, add_to_cart)

            else:
                message = "incorect password"

        except User.DoesNotExist:
            message = "incorrect id"

    elif request.POST["choice"] == "create":
        name = request.POST["name"]

        try:
            u = User.objects.get(username=auth_email)
            message = "already exists"
        except User.DoesNotExist:
            u = User.objects.create_user(
                username=auth_email, password=password, first_name=name
            )

            number = request.POST["number"]
            street = request.POST["street"].lower()
            cplt = request.POST["cplt"].lower()
            cp = request.POST["cp"]
            city = request.POST["city"].lower()

            try:
                adress_form = Adress.objects.get(
                    numero=number,
                    rue=street,
                    complement=cplt,
                    code_postal=cp,
                    ville=city,
                )
            except Adress.DoesNotExist:
                adress_form = Adress.objects.create(
                    numero=number,
                    rue=street,
                    complement=cplt,
                    code_postal=cp,
                    ville=city,
                )

            client = Client.objects.create(
                user=u,
                phone=request.POST["phone"],
                fk_client_type=ClientType.objects.get(
                    type_client=request.POST["type"]),
                fk_adress=adress_form,
            )

            user = authenticate(username=auth_email, password=password)
            login(request, user)

            check_cart_session(request)
            cart = CartSession(request.session.get("cart"))
            cart.create_queryset(request)
            cart.to_cart_database(request, client, add_to_cart)

            message = "success"

    context = {"message": message}

    return JsonResponse(context)


def profil(request, info="show"):
    """If request method is GET : load template to display profil infos of

store/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>farm</title>
  <link href="{% static 'store/css/bs_css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'store/css/style.css' %}" rel="stylesheet">
  <link rel="icon" type="image/png" href="{%static 'store/img/logo.png'%}" />
</head>

<body>
  <div class="fixed-top">
    <nav class="navbar navbar-dark navbar-expand-lg ">
      <a class="navbar-brand" href="{%url 'store:index'%}">
        <img src="{%static 'store/img/logo.png'%}" width="35" height="35" alt="logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{%url 'store:webmarket'%}">Marché en ligne</a>
          <a class="nav-item nav-link" href="{%url 'store:marketplaces'%}">Points de vente</a>
          {%if request.user.is_authenticated%}
          <a class="nav-item nav-link" href="{%url 'store:account'%}">Compte</a>
          {%else%}
          <a class="nav-item nav-link" data-toggle="modal" data-target="#ModalLogin" href="#">Login</a>
          {%endif%}
          <a class="nav-item nav-link" href="{%url 'store:cart'%}">Mon panier</a>
        </div>
      </div>
    </nav>
    {%if messageadmin%}
    <div id="adminmessage">
      <p class="py-1 px-3"> {{messageadmin}} </p>
    </div>
    {%endif%}
  </div>



{%include "store/modallogin.html"%}


{%block content%}{%endblock%}


<footer class="footer pt-5">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-12 text-center">
        <h5>AUX JARDINS GOURMANDS</h5>
        <p>rue du beau champs, Quesnoy </p>
        <a href="https://fr-fr.facebook.com/">
          <img class="network" src="{%static 'store/img/f_logo.png'%}" alt="">
        </a>
        <a href="https://www.instagram.com/?hl=fr">
          <img class="network ml-3" id="insta" src="{%static 'store/img/insta_logo.png'%}" alt="">
        </a>
    </div>
  </div>
    <div class="row">
      <div class="col-12 text-right pb-3">
        <a href="https://github.com/GregDupl" id="copyright">&copy; Grégoire Duponchel</a>
      </div>
    </div>
  </div>
</footer>


<script src="{% static 'store/js/jquery.slim.min.js' %}"></script>
<script src="{% static 'store/js/jquery-3.5.1.js' %}"></script>
<script src="{% static 'store/js/bs_js/bootstrap.min.js' %}"></script>
<script src="{% static 'store/js/bs_js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'store/js/script.js' %}"></script>
</body>
</html>

store/templates/store/cart.html
{%extends "store/base.html"%}
{% load static %}

{%block content%}
<section class="mt-2">
  <div class="container">
    <div class="row h-100">
      <div class="col-sm-2 d-none d-md-block text-center my-5">
        <img src="{% static 'store/img/aubergine.png' %}" alt="" class="img-fluid img-thumbnail dessin" id="radis">
      </div>
      <div class="col-12 col-md-8 my-auto">
        <div class="py-4 px-5 mt-5 border rounded cart_list" style="background-color:white">
          <h5>MON PANIER</h5>
          <div class="" style="color:red"> {{message}} </div>
          {%if cart%}
        <table class="table mt-4" data-url="{%url 'store:cart'%}">
          <thead class="">
            <tr>
              <th scope="col" colspan="2">Produit</th>
              <th scope="col">Quantité</th>
              <th scope="col" style="text-align : right">Total</th>
            </tr>
          </thead>
          <tbody>
            {%for elt in cart%}
              <tr data-product="{{elt.fk_variety.id}}" data-price="{{elt.fk_variety.price}}">
                <td style="width:7em">
                  <img src="{{elt.fk_variety.image.url}}" alt="" class="img-fluid mb-2 border rounded my-auto">
                </td>
                <td class="text-center">{{elt.fk_variety.fk_product.name|capfirst}} - {{elt.fk_variety.name}}</td>
                <td>

                {% with id=elt.fk_variety.id quantity=elt.quantity stock=elt.fk_variety.stock %}
                  {%include 'store/cartbutton.html'%}
                {%endwith%}

                </td>
                <td style="text-align : right" class="subtotal">{{elt.total}}</td>
              </tr>
            {%endfor%}
            <tr>
              <td colspan="4" style="text-align : right" id="total_cart">{{total}}</td>
            </tr>
          </tbody>
        </table>
        {%else%}
        <p class="my-5">Vous n'avez aucun produit dans votre panier pour l'instant. </p>
        {%endif%}
      </div>
        <div class="row my-5">
          <div class="col-6 text-center">
            <a href="{%url 'store:webmarket'%}">
              <button class="btn btn-outline-info" type="button" name="button">Continuez mon marché</button>
            </a>
          </div>
          <div class="col-6 text-center">
            {%if request.user.is_authenticated%}
            <button class="btn btn-info command_button" data-reservation="{%url 'store:reservation'%}" data-min= "{{minimum}}" id="command" type="button" name="button" {% if total < minimum %}disabled{%endif%}>Vérifier le stock et passer commande</button>
            {%else%}
            <button class="btn btn-info command_button" data-toggle="modal" data-target="#ModalLogin" data-min= "{{minimum}}" type="button" name="button" {% if total < minimum %}disabled{%endif%}>Vérifier le stock et passer commande</button>
            {%endif%}
            <p class="text-center mt-3"> Minimum de commande : {{minimum}}€ </p>
          </div>
        </div>
      </div>
      <div class="col-sm-2 d-none d-md-block text-center my-auto">
        <img src="{% static 'store/img/artichaut.png' %}" alt="" class="img-fluid img-thumbnail dessin" id="aubergine">
      </div>
    </div>
  </div>
</section>
{%endblock%}

store/templates/store/cartbutton.html
<div class="cart_interface" data-id={{id}}>
{%if stock == 0%}
<button type="submit" class="btn btn-info my-2 add" style="display:block" data-id={{id}} data-url="{%url 'store:adding_cart'%}" name="button" disabled>+</button>
{%else%}
  {%if quantity%}
  <div class="modif" style="display:block" data-url="{%url 'store:cart'%}">
    {%if quantity == 1%}
      <button class=" btn btn-info changebutton minus del"> del </button>
    {%else%}
      <button class=" btn btn-info changebutton minus"> - </button>
    {%endif%}
    <input class=" quantity" type="text" inputmode="numeric" max={{stock}} value={{quantity}} min="1">
    {%if quantity == stock %}
    <button class=" btn btn-info changebutton plus disabled"> max </button>
    {%else%}
    <button class=" btn btn-info changebutton plus"> + </button>
    {%endif%}
  </div>
  <button type="submit" class="btn btn-info my-2 add" style="display:none" data-id={{id}} data-url="{%url 'store:adding_cart'%}" name="button">+</button>

  {%else%}
  <div class="modif" style="display:none" data-url="{%url 'store:cart'%}">
    <button class=" btn btn-info changebutton minus del"> del </button>
    <input class="quantity" type="text" inputmode="numeric" max={{stock}} value="1" min="1">
    <button class=" btn btn-info changebutton plus"> + </button>
  </div>
  <button type="submit" class="btn btn-info my-2 add" style="display:block" data-id={{id}} data-url="{%url 'store:adding_cart'%}" name="button">+</button>
  {%endif%}


{%endif%}
</div>

store/templates/store/profil.html
{%extends "store/base.html"%}
{% load static %}

{%block content%}
<section class="my-3">
  <div class="container">
    <div class="row h-100 pb-5 mb-5">
      <div class="col-md-6">
        <div class="presentation">
          <h4>Mes commandes</h4>


          <div class="my-3" id="message">{{ message }}</div>
          <div class="row">
            <div class="col-12">
              <hr>
              <h5>COMMANDES EN COURS</h5>
              {%if actual_order%}
              <div class="row my-3">
                <div class="col-12" id="accordion1">

                  {%for order in actual_order%}
                  <div class="card">
                    <div class="card-header" id="heading{{order.pk}}">
                      <h5 class="mb-0">
                        <button class="btn btn-link title_card" data-toggle="collapse" data-target="#collapse{{order.pk}}" aria-expanded="true" aria-controls="collapse{{order.pk}}">
                          Numéro {{order.fk_order.pk}} - validée le {{order.date_creation|date:"SHORT_DATE_FORMAT"}}
                        </button>
                        <button class="btn btn-light btn-sm my-auto float-right remove_order" data-url="{%url 'store:remove'%}" data-id="{{order.fk_order.pk}}" type="button" name="button">Annuler</button>
                      </h5>
                    </div>

                    <div id="collapse{{order.pk}}" class="collapse" aria-labelledby="heading{{order.pk}}" data-parent="#accordion1">
                      <div class="card-body">
                        <div class="mb-4">
                          {%if order.fk_order.fk_direct_withdrawal%}
                          En retrait direct - {{order.fk_order.fk_direct_withdrawal.fk_collect_location.name}}
                          {%elif order.fk_order.fk_locker%}
                          En click&collect - {{order.fk_order.fk_locker.fk_collect_location.name}}  - casier n° {{order.fk_order.fk_locker.number}}
                          {%else%}
                          Livraison - {{order.fk_order.fk_delivery.fk_delivery_slot.fk_time_slot.fk_day.name}}
                          {%endif%}
                        </div>
                        {%for elt in order.queryset_variety%}
                        <div class="row my-1 align-items-center">
                          <div class="col-3">
                            <img class="rounded mr-3" src="{{elt.fk_variety.image.url}}" alt="">
                          </div>
                          <div class="col-6 text-left">
                              {{elt.fk_variety.fk_product.name|capfirst}} - {{elt.fk_variety}}
                          </div>
                          <div class="col-3 text-right">
                            qté : {{elt.quantity}}
                          </div>
                        </div>
                        {%endfor%}
                      </div>
                    </div>
                  </div>
                  {%endfor%}

                </div>
              </div>
              {%else%}
              <div class="row">
                <div class="col-12">
                  <p>Vous n'avez aucune commande en cours</p>
                </div>
              </div>
              {%endif%}
            </div>

            {%if past_order%}
            <div class="col-12">
              <hr>
              <h5>COMMANDES PASSEES</h5>
              <div class="row my-3">
              {%for order in past_order%}
                <div class="col-12">
                  <p class="my-auto"></p>
                </div>
              {%endfor%}
              <div class="col-12" id="accordion2">
                {%for order in past_order%}
                <div class="card">
                  <div class="card-header" id="heading{{order.pk}}">
                    <h5 class="mb-0">
                      <button class="btn btn-link title_card" data-toggle="collapse" data-target="#collapse{{order.pk}}" aria-expanded="true" aria-controls="collapse{{order.pk}}">
                        N° {{order.fk_order.pk}} - terminée le {{order.date_end|date:"SHORT_DATE_FORMAT"}}
                      </button>
                    </h5>
                  </div>

                  <div id="collapse{{order.pk}}" class="collapse" aria-labelledby="heading{{order.pk}}" data-parent="#accordion2">
                    <div class="card-body">
                      {%for elt in order.queryset_variety%}
                      <div class="row my-1 align-items-center">
                        <div class="col-3">
                          <img class="rounded mr-3" src="{{elt.fk_variety.image.url}}" alt="">
                        </div>
                        <div class="col-6 text-left">
                            {{elt.fk_variety.fk_product.name|capfirst}} - {{elt.fk_variety}}
                        </div>
                        <div class="col-3 text-right">
                          qté : {{elt.quantity}}
                        </div>
                      </div>
                      {%endfor%}
                    </div>
                  </div>
                </div>
                {%endfor%}

              </div>
            </div>
            </div>
            {%endif%}

          </div>
        </div>
      </div>

      <div class="offset-md-1 col-md-5">
        <div class="row">
          <div class="presentation col-12">
            <div class="row">
              <div class="col-9">
                <h4>Mes infos</h4>
              </div>
              <div class="col-3">
                <button class="btn btn-link btn-sm" id="update_infos_button" type="button" name="button">Modifier</button>
              </div>

            </div>
            <hr>
            <div class="row">
              <div class="col-12">
                <div id="update_message" class="py-3" style="color:red"></div>
                <!-- DISPLAY INFOS PROFIL -->
                <div class="" id="infosprofil" style="display:block">
                  <p>Nom : {{client.user.first_name|capfirst}}</p>
                  <p>email : {{email}} </p>
                  <p>adresse :
                    {{client.fk_adress.numero}},
                    {{client.fk_adress.rue}}
                    {%if client.fk_adress.complement%}
                    {{client.fk_adress.complement}}
                    {%endif%}
                    {{client.fk_adress.code_postal}}
                    {{client.fk_adress.ville|capfirst}}</p>
                </div>
                <!-- FORM TO UPDATE INFOS PROFIL -->
                <form class="" id="update_infos_form" action="{%url 'store:account'%}" method="post" style="display:none" >
                  <div class="message"></div>
                  <div class="form-group row">
                    <div class="col-sm-12">
                      <input type="email" class="form-control" name="mail" value="{{email}}" required>
                    </div>
                  </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                        <input type="text" class="form-control req" name="name" value="{{client.user.first_name|capfirst}}" required>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                        {%if client.phone%}
                        <input type="tel" class="form-control" name="phone" value="{{client.phone}}" minlength=10>
                        {%else%}
                        <input type="tel" class="form-control" name="phone" placeholder="0606060606" minlength=10>
                        {%endif%}

                      </div>
                    </div>

                  <div class="form-group row">
                    <div class="col-sm-12">
                      <input type="number" class="form-control my-2 req" name="number" value="{{client.fk_adress.numero}}" required>
                      <input type="text" class="form-control my-2 req" name="rue" value="{{client.fk_adress.rue}}" required>
                      {%if client.fk_adress.complement%}
                      <input type="text" class="form-control my-2" name="cplt" value="{{client.fk_adress.complement}}">
                      {%else%}
                      <input type="text" class="form-control my-2" name="cplt" placeholder="Complément d'adresse">
                      {%endif%}
                      <input type="text" class="form-control my-2 req" name="code_postal" value="{{client.fk_adress.code_postal}}" required>
                      <input type="text" class="form-control my-2 req" name="ville" value="{{client.fk_adress.ville|capfirst}}" required>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-9">
                      <input type="password" class="form-control" name="password" placeholder="Entrez votre mot de passe" required>
                    </div>
                    <div class="col-3 pl-0">
                      <button class="btn btn-info btn-sm btn-block py-2" type="submit" name="button">Envoyer</button>
                    </div>
                  </div>
                </form>

                <!-- FORM TO UPDATE PASSWORD -->
                <form class="" id="update_password_form" action="" method="post" style="display:none">
                  <div class="message"></div>
                  <div class="form-group row">
                    <div class="col-sm-12">
                      <input type="password" class="form-control py-2" name="newpassword" placeholder="Choisir un nouveau mot de passe" required>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-sm-12">
                      <input type="password" class="form-control" name="confirmpassword" placeholder="Confirmer votre nouveau mot de passe" required>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-9">
                      <input type="password" class="form-control py-2" name="actualpassword" placeholder="Mot de passe actuel" required>
                    </div>
                    <div class="col-3 pl-0">
                      <button class="btn btn-info btn-sm btn-block py-2" type="submit" name="button">Envoyer</button>
                    </div>
                  </div>

                </form>

                <div class="mt-5">
                  <button class="btn btn-link btn-sm float-right" id="update_password_button" type="button" name="button">Changer de mot de passe</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5 pb-1">
          <div class="offset-md-5 col-md-7">
            <a class="btn btn-info btn-sm btn-block" id="logoutbutton" href="{%url 'store:logout'%}">Se déconnecter</a>
          </div>
        </div>
        <hr>
        <div class="row pt-1">
          <div class="offset-5 col-md-7">
            <a class="btn btn-link btn-sm btn-block text-right" style="color : red" id="deletebutton" href="#" style="display:block">Supprimer mon compte</a>
          <div class="alert alert-danger alert-dismissible fade show text-right" id="alertdelete" role="alert" style="display:none">
            <strong> Êtes-vous sûr ? </strong> Cette action est définitive !
            <a href="{%url 'store:delete_account'%}"><button class="btn btn-danger ml-1" type="button" name="button">oui</button></a>
            <button class="btn btn-secondary ml-1" id="abandon" type="button" name="button"> non </button>
          </div>
        </div>
        </div>

      </div>
    </div>


  </div>
</section>
{%endblock%}